import { ArrowLeft, Megaphone } from "lucide-react"
import { redirect } from "next/navigation"
import { DashboardSignOutButton } from "@/components/dashboard-sign-out-button"
import { createSupabaseServerClient, isSupabaseConfigured } from "@/lib/supabase/server"
import { MarketingExport } from "@/components/marketing-export"

export default async function MarketingAudiencePage() {
  if (!isSupabaseConfigured()) redirect("/dashboard")
  const supabase = await createSupabaseServerClient()
  if (!supabase) redirect("/dashboard")
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) redirect("/dashboard/login")
  const { data } = await supabase.from("audit_leads").select("id, lead_name, email, lead_type, lead_source, marketing_consent_at, created_at").eq("marketing_consent", true).order("marketing_consent_at", { ascending: false }).limit(500)
  const contacts = (data ?? []) as Array<{ id: string; lead_name: string | null; email: string; lead_type: string | null; lead_source: string | null; marketing_consent_at: string | null; created_at: string }>
  return <main className="min-h-screen bg-slate-50 px-5 py-8 text-slate-950 sm:px-8"><div className="mx-auto max-w-6xl"><header className="flex flex-wrap items-end justify-between gap-5 border-b border-slate-200 pb-7"><div><a href="/dashboard" className="inline-flex items-center gap-2 text-sm font-semibold text-sky-700 hover:text-sky-900"><ArrowLeft className="size-4" />Overview</a><div className="mt-5 flex items-center gap-3"><span className="flex size-10 items-center justify-center rounded-xl bg-emerald-100 text-emerald-700"><Megaphone className="size-5" /></span><div><p className="text-sm font-bold uppercase tracking-[.16em] text-emerald-700">Permission-based audience</p><h1 className="mt-1 text-3xl font-bold tracking-tight">Marketing audience</h1></div></div><p className="mt-4 max-w-2xl text-sm leading-6 text-slate-600">Only contacts who explicitly opted in are shown here. Keep this list separate from ordinary enquiries and honour unsubscribe requests.</p></div><DashboardSignOutButton /></header><section className="mt-8 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-wrap items-center gap-3 border-b border-slate-200 p-5"><div><h2 className="font-bold">Opted-in contacts</h2><p className="mt-1 text-sm text-slate-500">{contacts.length} contact{contacts.length === 1 ? "" : "s"} available for future updates.</p></div><MarketingExport contacts={contacts} /></div>{contacts.length ? <div className="divide-y divide-slate-100">{contacts.map((contact) => <article key={contact.id} className="flex flex-col gap-3 p-5 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><p className="font-semibold">{contact.lead_name || "Website contact"}</p><p className="mt-1 text-sm text-slate-600">{contact.email}</p></div><div className="flex flex-wrap items-center gap-2 text-xs"><span className="rounded-full bg-sky-50 px-2.5 py-1 font-semibold text-sky-700">{contact.lead_type || "General enquiry"}</span><span className="rounded-full bg-slate-100 px-2.5 py-1 font-semibold text-slate-600">{contact.lead_source || "Contact form"}</span><span className="text-slate-400">Opted in {contact.marketing_consent_at ? new Date(contact.marketing_consent_at).toLocaleDateString() : "—"}</span></div><a href={`mailto:${contact.email}`} className="inline-flex min-h-10 items-center justify-center rounded-xl border border-slate-200 px-3 text-sm font-semibold text-slate-700 hover:border-sky-300 hover:text-sky-800">Email</a></article>)}</div> : <div className="p-12 text-center text-sm text-slate-600">No marketing opt-ins yet. Contacts will appear here only after they choose the marketing updates checkbox.</div>}</section></div></main>
}
