import { ArrowLeft, BarChart3, FileText, HeartPulse, Mail, Rocket, Sparkles } from "lucide-react"

const features = [
  { title: "Content manager", description: "Edit service pages, landing-page copy, blog posts, and SEO metadata from one place.", icon: FileText, status: "In progress", tone: "bg-violet-50 text-violet-700", href: "/dashboard/content", action: "Open content manager" },
  { title: "Site health monitor", description: "Schedule recurring checks for uptime, SEO signals, performance, and broken links.", icon: HeartPulse, status: "In progress", tone: "bg-emerald-50 text-emerald-700", href: "/dashboard/health", action: "Open health checks" },
  { title: "Client-ready reports", description: "Create branded PDF reports, compare audits over time, and share a secure report link.", icon: BarChart3, status: "In progress", tone: "bg-sky-50 text-sky-700", href: "/dashboard/reports", action: "Open report library" },
  { title: "Email campaigns", description: "Send permission-based updates to marketing opt-ins with unsubscribe tracking.", icon: Mail, status: "Planned", tone: "bg-amber-50 text-amber-700", href: "/dashboard/marketing", action: "Open marketing audience" },
]

export default function UpcomingPage() {
  return <main className="min-h-screen bg-slate-50 px-5 py-8 text-slate-950 sm:px-8"><div className="mx-auto max-w-6xl"><header className="border-b border-slate-200 pb-7"><a href="/dashboard" className="inline-flex items-center gap-2 text-sm font-semibold text-sky-700 hover:text-sky-900"><ArrowLeft className="size-4" />Overview</a><div className="mt-5 flex items-start gap-3"><span className="flex size-11 items-center justify-center rounded-2xl bg-sky-100 text-sky-700"><Rocket className="size-5" /></span><div><p className="text-sm font-bold uppercase tracking-[.16em] text-sky-700">Product roadmap</p><h1 className="mt-1 text-3xl font-bold tracking-tight">Upcoming features</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-600">A clear view of the next tools planned for your admin workspace.</p></div></div></header><section className="mt-8 grid gap-5 sm:grid-cols-2">{features.map((feature) => { const Icon = feature.icon; return <article key={feature.title} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-start justify-between gap-4"><span className={`flex size-11 items-center justify-center rounded-xl ${feature.tone}`}><Icon className="size-5" /></span><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-bold text-slate-600">{feature.status}</span></div><h2 className="mt-5 text-xl font-bold">{feature.title}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{feature.description}</p><a href={feature.href} className="mt-5 inline-flex text-sm font-semibold text-sky-700 hover:text-sky-900">{feature.action} →</a></article> })}</section><section className="mt-8 rounded-2xl bg-slate-950 p-6 text-white shadow-sm sm:p-8"><div className="flex items-start gap-4"><Sparkles className="mt-1 size-5 shrink-0 text-sky-300" /><div><p className="text-sm font-bold uppercase tracking-[.14em] text-sky-300">How this grows</p><h2 className="mt-2 text-2xl font-bold">One workspace for the whole business.</h2><a href="/dashboard/leads" className="mt-5 inline-flex rounded-xl bg-white px-4 py-3 text-sm font-semibold text-slate-950">Open Leads Inbox →</a></div></div></section></div></main>
}
