"use client"

import { BarChart3, CircleAlert, TrendingUp } from "lucide-react"
import type { DashboardLead } from "@/components/dashboard-lead-list"
const dateKey = (date: Date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`
const today = new Date(new Date().getFullYear(), new Date().getMonth(), new Date().getDate())

export function DashboardAnalytics({ leads }: { leads: DashboardLead[] }) {
  const won = leads.filter((lead) => lead.status === "Won")
  const wonValue = won.reduce((total, lead) => total + Number(lead.deal_value || 0), 0)
  const conversion = leads.length ? Math.round((won.length / leads.length) * 100) : 0
  const thisMonth = leads.filter((lead) => new Date(lead.created_at).getMonth() === new Date().getMonth())
  const average = (key: "performance" | "seo") => { const values = thisMonth.map((lead) => lead[key]).filter((value): value is number => typeof value === "number"); return values.length ? Math.round(values.reduce((a, b) => a + b, 0) / values.length) : "—" }
  const overdue = leads.filter((lead) => (lead.follow_up_at && lead.follow_up_at < dateKey(today)) || (lead.re_audit_at && lead.re_audit_at < dateKey(today)))
  const dueToday = leads.filter((lead) => lead.follow_up_at === dateKey(today) || lead.re_audit_at === dateKey(today))
  const high = leads.filter((lead) => lead.priority === "high" && !["Won", "Not a fit"].includes(lead.status))
  const focus = [...overdue, ...dueToday, ...high].filter((lead, index, all) => all.findIndex((item) => item.id === lead.id) === index).slice(0, 5)
  return <section className="mt-8 space-y-5"><div className="rounded-2xl bg-slate-950 p-6 text-white shadow-sm"><div className="flex items-center gap-3"><CircleAlert className="size-5 text-sky-300" /><div><p className="text-sm font-bold uppercase tracking-[.14em] text-sky-200">Today&apos;s command center</p><h2 className="mt-1 text-xl font-bold">Focus on the work most likely to move forward.</h2></div></div><div className="mt-5 grid gap-3 sm:grid-cols-4"><Metric href="/dashboard?view=follow-up" label="Overdue" value={overdue.length} /><Metric href="/dashboard?view=high" label="High priority" value={high.length} /><Metric href="/dashboard?view=follow-up" label="Due today" value={dueToday.length} /><Metric href="/dashboard?view=won" label="Won value" value={wonValue.toLocaleString(undefined, { maximumFractionDigits: 2 })} /></div>{focus.length > 0 && <div className="mt-5 flex flex-wrap gap-2">{focus.map((lead) => <a key={lead.id} href={`/dashboard/leads/${lead.id}`} className="rounded-lg bg-white px-3 py-2 text-sm font-semibold text-slate-950">{lead.website_url}</a>)}</div>}</div><div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><BarChart3 className="size-5 text-sky-700" /><div><p className="text-sm font-bold uppercase tracking-[.14em] text-sky-700">Dashboard analytics</p><h2 className="mt-1 text-xl font-bold">Lead and score trends</h2></div></div><div className="mt-5 flex flex-wrap gap-2">{[["all", "All leads"], ["high", "High priority"], ["follow-up", "Needs follow-up"], ["won", "Won leads"]].map(([key, label]) => <a key={key} href={key === "all" ? "/dashboard" : `/dashboard?view=${key}`} className="rounded-full border border-slate-200 bg-slate-50 px-3 py-2 text-sm font-semibold text-slate-700">{label}</a>)}</div><div className="mt-6 grid gap-4 sm:grid-cols-3"><article className="rounded-xl border border-slate-200 p-5"><p className="text-sm font-semibold text-slate-600">This month&apos;s audits</p><p className="mt-2 text-3xl font-bold">{thisMonth.length}</p></article><article className="rounded-xl bg-slate-950 p-5 text-white"><TrendingUp className="size-5 text-sky-300" /><p className="mt-3 text-sm font-semibold text-sky-100">Lead conversion</p><p className="mt-1 text-3xl font-bold">{conversion}%</p></article><article className="rounded-xl border border-emerald-200 bg-emerald-50 p-5"><p className="text-sm font-semibold text-emerald-900">Current averages</p><p className="mt-2 text-lg font-bold text-emerald-950">Mobile {average("performance")} · SEO {average("seo")}</p></article></div></div></section>
}
function Metric({ href, label, value }: { href: string; label: string; value: string | number }) { return <a href={href} className="rounded-xl bg-white/10 p-4 transition hover:bg-white/15"><p className="text-sm font-semibold text-sky-100">{label}</p><p className="mt-1 text-3xl font-bold">{value}</p></a> }
