"use client"

import { useMemo, useState } from "react"
import { CalendarDays, ChevronLeft, ChevronRight } from "lucide-react"
import type { DashboardLead } from "@/components/dashboard-lead-list"

type CalendarEvent = { lead: DashboardLead; type: "Follow-up" | "Re-audit"; date: string }
const dayKey = (date: Date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`
const calendarDate = (value: string) => new Date(`${value}T00:00:00`)

export function DashboardCalendar({ leads }: { leads: DashboardLead[] }) {
  const [month, setMonth] = useState(() => new Date(new Date().getFullYear(), new Date().getMonth(), 1))
  const events = useMemo<CalendarEvent[]>(() => leads.flatMap((lead) => [lead.follow_up_at ? { lead, type: "Follow-up" as const, date: lead.follow_up_at } : null, lead.re_audit_at ? { lead, type: "Re-audit" as const, date: lead.re_audit_at } : null].filter((event): event is CalendarEvent => Boolean(event))), [leads])
  const monthEvents = events.filter((event) => { const date = calendarDate(event.date); return date.getFullYear() === month.getFullYear() && date.getMonth() === month.getMonth() })
  const firstDay = new Date(month.getFullYear(), month.getMonth(), 1)
  const start = new Date(month.getFullYear(), month.getMonth(), 1 - firstDay.getDay())
  const days = Array.from({ length: 42 }, (_, index) => new Date(start.getFullYear(), start.getMonth(), start.getDate() + index))
  const today = dayKey(new Date())

  return <section className="mt-8 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex flex-wrap items-center gap-3"><CalendarDays className="size-5 text-sky-700" /><div><p className="text-sm font-bold uppercase tracking-[.14em] text-sky-700">Follow-up calendar</p><h2 className="mt-1 text-xl font-bold">Scheduled lead activity</h2></div><div className="ml-auto flex items-center gap-2"><button type="button" onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() - 1, 1))} aria-label="Previous month" className="rounded-lg border border-slate-200 p-2 text-slate-700 transition hover:bg-slate-50"><ChevronLeft className="size-4" /></button><p className="min-w-28 text-center text-sm font-bold">{month.toLocaleDateString("en-US", { month: "long", year: "numeric" })}</p><button type="button" onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() + 1, 1))} aria-label="Next month" className="rounded-lg border border-slate-200 p-2 text-slate-700 transition hover:bg-slate-50"><ChevronRight className="size-4" /></button></div></div><div className="mt-6 grid grid-cols-7 gap-px overflow-hidden rounded-xl border border-slate-200 bg-slate-200">{["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"].map((day) => <div key={day} className="bg-slate-50 px-2 py-2 text-center text-xs font-bold uppercase tracking-[.08em] text-slate-500">{day}</div>)}{days.map((date) => { const key = dayKey(date); const dateEvents = events.filter((event) => event.date === key); const currentMonth = date.getMonth() === month.getMonth(); return <div key={key} className={`min-h-22 bg-white p-2 ${currentMonth ? "" : "bg-slate-50 text-slate-400"}`}><p className={`flex size-6 items-center justify-center rounded-full text-xs font-semibold ${key === today ? "bg-sky-700 text-white" : ""}`}>{date.getDate()}</p><div className="mt-1 space-y-1">{dateEvents.slice(0, 2).map((event, index) => <a key={`${event.lead.id}-${event.type}-${index}`} href={`/dashboard/leads/${event.lead.id}`} className={`block truncate rounded px-1.5 py-1 text-[10px] font-bold leading-none hover:opacity-80 ${event.type === "Follow-up" ? "bg-sky-100 text-sky-900" : "bg-violet-100 text-violet-900"}`} title={`${event.type}: ${event.lead.website_url}`}>{event.type}: {event.lead.website_url}</a>)}{dateEvents.length > 2 && <p className="px-1 text-[10px] font-semibold text-slate-500">+{dateEvents.length - 2} more</p>}</div></div> })}</div><div className="mt-5 flex flex-wrap items-center gap-3 text-xs text-slate-600"><span className="inline-flex items-center gap-1.5"><span className="size-2 rounded-full bg-sky-500" />Follow-up</span><span className="inline-flex items-center gap-1.5"><span className="size-2 rounded-full bg-violet-500" />Re-audit</span><span className="ml-auto">{monthEvents.length} scheduled item{monthEvents.length === 1 ? "" : "s"} this month</span></div></section>
}
