"use client"

import { BellRing, Check, CircleAlert, Info, Sparkles } from "lucide-react"
import { useEffect, useState } from "react"

type Notification = { id: string; title: string; message: string; kind: "info" | "success" | "warning" | "error"; href: string | null; is_read: boolean; created_at: string }

export function DashboardNotificationsPage() {
  const [notifications, setNotifications] = useState<Notification[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState("")
  useEffect(() => { void fetch("/api/dashboard/notifications", { cache: "no-store" }).then(async (response) => { const payload = await response.json(); if (!response.ok) setError(payload.error ?? "Could not load notifications."); else setNotifications(payload.notifications ?? []); setLoading(false) }) }, [])
  const markAllRead = async () => { await fetch("/api/dashboard/notifications", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ all: true }) }); setNotifications((current) => current.map((item) => ({ ...item, is_read: true }))) }
  const markRead = async (notification: Notification) => { if (!notification.is_read) { await fetch("/api/dashboard/notifications", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: notification.id }) }); setNotifications((current) => current.map((item) => item.id === notification.id ? { ...item, is_read: true } : item)) } }
  const icon = (kind: Notification["kind"]) => kind === "error" ? <CircleAlert className="size-5 text-rose-600" /> : kind === "warning" ? <CircleAlert className="size-5 text-amber-600" /> : kind === "success" ? <Check className="size-5 text-emerald-600" /> : <Info className="size-5 text-sky-600" />
  return <main className="min-h-screen bg-slate-50 px-5 py-8 text-slate-950 sm:px-8"><div className="mx-auto max-w-4xl"><header className="flex flex-wrap items-end justify-between gap-4 border-b border-slate-200 pb-7"><div><p className="text-sm font-bold uppercase tracking-[.16em] text-sky-700">Workspace inbox</p><h1 className="mt-2 text-3xl font-bold tracking-tight">Notifications</h1><p className="mt-3 text-sm leading-6 text-slate-600">Important updates from users, leads, and campaigns.</p></div><button type="button" onClick={() => void markAllRead()} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-semibold text-slate-700"><Check className="size-4" />Mark all read</button></header>{error && <p className="mt-6 rounded-xl bg-rose-50 p-4 text-sm text-rose-800">{error}</p>}{loading ? <p className="mt-8 text-sm text-slate-500">Loading notifications...</p> : <section className="mt-8 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">{notifications.length ? <div className="divide-y divide-slate-100">{notifications.map((notification) => <a key={notification.id} href={notification.href ?? "#"} onClick={() => void markRead(notification)} className={`flex gap-4 p-5 transition hover:bg-slate-50 ${notification.is_read ? "opacity-70" : "bg-sky-50/40"}`}><span className="mt-0.5 flex size-10 shrink-0 items-center justify-center rounded-xl bg-white shadow-sm">{icon(notification.kind)}</span><span className="min-w-0 flex-1"><span className="flex items-center gap-2"><span className="font-bold">{notification.title}</span>{!notification.is_read && <span className="size-2 rounded-full bg-sky-500" />}</span><span className="mt-1 block text-sm leading-6 text-slate-600">{notification.message}</span><time className="mt-2 block text-xs text-slate-400">{new Date(notification.created_at).toLocaleString()}</time></span></a>)}</div> : <div className="p-12 text-center"><Sparkles className="mx-auto size-8 text-slate-300" /><p className="mt-3 text-sm text-slate-500">You’re all caught up.</p></div>}</section>}</div></main>
}
