"use client"

import { useEffect, useState } from "react"
import { Save, Tags } from "lucide-react"
import { createSupabaseBrowserClient } from "@/lib/supabase/client"

export function LeadOrganization({ leadId }: { leadId: string }) {
  const [priority, setPriority] = useState("normal")
  const [tags, setTags] = useState("")
  const [state, setState] = useState<"loading" | "idle" | "saving" | "saved" | "error">("loading")
  useEffect(() => { const load = async () => { const supabase = createSupabaseBrowserClient(); if (!supabase) return setState("error"); const { data } = await supabase.from("audit_leads").select("priority, tags").eq("id", leadId).single(); if (data) { setPriority(data.priority ?? "normal"); setTags(Array.isArray(data.tags) ? data.tags.join(", ") : "") }; setState("idle") }; void load() }, [leadId])
  const save = async () => { setState("saving"); const supabase = createSupabaseBrowserClient(); if (!supabase) return setState("error"); const cleanTags = Array.from(new Set(tags.split(",").map((tag) => tag.trim()).filter(Boolean))).slice(0, 10); const { error } = await supabase.from("audit_leads").update({ priority, tags: cleanTags }).eq("id", leadId); setState(error ? "error" : "saved") }
  return <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex gap-3"><Tags className="mt-0.5 size-5 text-sky-700" /><div><p className="text-sm font-bold uppercase tracking-[.14em] text-sky-700">Lead organization</p><h2 className="mt-2 text-xl font-bold">Priority and tags</h2></div></div><div className="mt-5 grid gap-3"><label className="text-sm font-semibold">Priority<select value={priority} onChange={(event) => { setPriority(event.target.value); setState("idle") }} disabled={state === "loading"} className="mt-2 min-h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm font-medium"><option value="high">High priority</option><option value="normal">Normal priority</option><option value="low">Low priority</option></select></label><label className="text-sm font-semibold">Tags<input value={tags} onChange={(event) => { setTags(event.target.value); setState("idle") }} placeholder="SEO, warm lead, website redesign" disabled={state === "loading"} className="mt-2 min-h-11 w-full rounded-xl border border-slate-200 px-3 text-sm font-normal" /><span className="mt-2 block text-xs font-normal text-slate-500">Separate tags with commas.</span></label></div><div className="mt-4 flex flex-wrap gap-3"><button type="button" onClick={save} disabled={state === "loading" || state === "saving"} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-sky-700 px-4 text-sm font-semibold text-white disabled:opacity-60"><Save className="size-4" />{state === "saving" ? "Saving..." : "Save organization"}</button>{state === "saved" && <p className="self-center text-sm font-medium text-emerald-700">Saved.</p>}{state === "error" && <p className="self-center text-sm font-medium text-rose-700">Could not save. Run the organization SQL first.</p>}</div></section>
}
