"use client"

import { ArrowRight, Boxes, Database, FileSpreadsheet, Globe2, PackageCheck, Settings, Store } from "lucide-react"

const supportAreas = [
  { icon: Globe2, title: "Website content management", items: ["WordPress, Shopify, and Wix updates", "Pages, posts, images, menus, and formatting", "Content cleanup and website data entry"] },
  { icon: Store, title: "E-commerce product listings", items: ["Product titles, descriptions, categories, and images", "Attributes, pricing fields, tags, and variations", "Shopify, WooCommerce, and marketplace catalogs"] },
  { icon: PackageCheck, title: "Amazon catalog support", items: ["Product listing creation and updates", "Variations, attributes, product data, and research", "Spreadsheet-based catalog organization"] },
  { icon: Database, title: "Data entry & migration", items: ["Manual and bulk data entry", "Data cleanup, validation, and formatting", "Product, website, and business data transfers"] },
  { icon: FileSpreadsheet, title: "Research & spreadsheets", items: ["Web and product research", "Excel and Google Sheets support", "List building, collection, and PDF conversion"] },
  { icon: Settings, title: "Ongoing admin assistance", items: ["Recurring website and store tasks", "CRM, reporting, and online admin work", "Flexible support based on your workflow"] },
]

export function Projects() {
  return <section id="projects" className="relative overflow-hidden bg-slate-100 py-20 dark:bg-slate-900 sm:py-28"><div className="absolute -left-32 top-12 h-80 w-80 rounded-full bg-portfolio-primary/10 blur-3xl" /><div className="container relative mx-auto px-4"><div className="mx-auto mb-12 max-w-3xl text-center"><span className="inline-flex rounded-full border border-portfolio-primary/20 bg-card px-3 py-1 text-xs font-semibold uppercase tracking-[.16em] text-portfolio-primary shadow-sm">Support areas</span><h2 className="mt-5 text-4xl font-bold tracking-tight text-foreground sm:text-5xl">The online work I can take off your plate.</h2><p className="mt-4 text-lg text-muted-foreground">Choose a focused task or combine support areas for a workflow that fits your business.</p></div><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{supportAreas.map(area => { const Icon = area.icon; return <article key={area.title} className="group rounded-3xl border border-border bg-card p-6 shadow-sm transition duration-300 hover:-translate-y-1 hover:border-portfolio-primary/30 hover:shadow-xl"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-portfolio-primary/10 text-portfolio-primary"><Icon className="h-5 w-5" /></span><h3 className="mt-6 text-xl font-semibold text-foreground">{area.title}</h3><ul className="mt-4 space-y-2 text-sm leading-6 text-muted-foreground">{area.items.map(item => <li key={item} className="flex gap-2"><span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-portfolio-accent" />{item}</li>)}</ul></article> })}</div><div className="mt-8 text-center"><a href="#contact" className="inline-flex items-center gap-2 text-sm font-semibold text-portfolio-primary hover:underline">Not sure where your task fits? Send the details <ArrowRight className="h-4 w-4" /></a></div></div></section>
}
