"use client"

import { CheckCircle2, ClipboardList, MessageSquareText, Send, Sparkles } from "lucide-react"

const steps = [
  { icon: MessageSquareText, title: "1. Share the task", text: "Tell me the platform, your goal, deadline, and any access, files, or links that will help." },
  { icon: ClipboardList, title: "2. Get a clear plan", text: "I’ll confirm the scope, priorities, and the practical next step before the work begins." },
  { icon: CheckCircle2, title: "3. Review completed work", text: "Receive organized updates and completed work that is ready for your review or hand-off." },
]

export function Testimonials() {
  return <section id="testimonials" className="relative overflow-hidden bg-background py-20 md:py-28"><div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_80%_15%,color-mix(in_oklab,var(--portfolio-primary)_10%,transparent),transparent_28rem)]" /><div className="container relative mx-auto px-4"><div className="mx-auto mb-12 max-w-2xl text-center md:mb-16"><div className="mb-4 inline-flex items-center gap-2 rounded-full border border-portfolio-primary/20 bg-portfolio-primary/10 px-3 py-1 text-sm font-medium text-portfolio-primary"><Sparkles className="h-4 w-4" />Simple and organized</div><h2 className="mb-4 text-3xl font-bold tracking-tight text-foreground md:text-5xl">A straightforward way to get support.</h2><p className="text-lg leading-relaxed text-muted-foreground">Clear communication and careful work matter whether you need one update or reliable ongoing assistance.</p></div><div className="mx-auto grid max-w-5xl gap-5 md:grid-cols-3">{steps.map(step => { const Icon = step.icon; return <article key={step.title} className="rounded-3xl border border-border bg-card p-7 shadow-sm transition duration-300 hover:-translate-y-1 hover:border-portfolio-primary/30 hover:shadow-xl"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-portfolio-primary/10 text-portfolio-primary"><Icon className="h-5 w-5" /></span><h3 className="mt-6 text-xl font-semibold text-foreground">{step.title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{step.text}</p></article> })}</div><div className="mx-auto mt-6 flex max-w-5xl flex-col gap-4 rounded-3xl border border-portfolio-primary/20 bg-portfolio-primary/5 p-6 sm:flex-row sm:items-center sm:justify-between sm:p-8"><div><p className="font-semibold text-foreground">Have a task ready to hand over?</p><p className="mt-1 text-sm text-muted-foreground">Send the details and I’ll help you choose the most useful next step.</p></div><a href="#contact" className="inline-flex w-fit items-center gap-2 rounded-xl bg-portfolio-primary px-4 py-2.5 text-sm font-semibold text-portfolio-primary-foreground shadow-sm hover:bg-portfolio-primary/90">Send your request <Send className="h-4 w-4" /></a></div></div></section>
}
