"use client"
import { useState } from "react"

export default function FreeAudit() {
  const [url, setUrl] = useState(""); const [email, setEmail] = useState(""); const [report, setReport] = useState<any>(); const [error, setError] = useState(""); const [loading, setLoading] = useState(false); const [saved, setSaved] = useState(false)
  const audit = async (event: React.FormEvent) => { event.preventDefault(); setError(""); setLoading(true); const response = await fetch("/api/audit", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ url }) }); const data = await response.json(); setLoading(false); if (!response.ok) return setError(data.error); setReport(data) }
  const saveLead = async () => { if (!email) return setError("Enter your email address."); const response = await fetch("/api/contact", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: "Free audit visitor", email, service: "Something else", timeline: "Free website audit", platform: "Website audit", websiteUrl: url, budget: "Not specified", message: `Free audit consent: Yes. Website: ${url}. Performance: ${report.performance}. SEO: ${report.seo}.`, sendChecklist: false }) }); if (!response.ok) return setError("Could not save your audit request."); setSaved(true) }
  return <main className="min-h-screen bg-background p-6 sm:p-10"><div className="mx-auto max-w-2xl rounded-3xl border border-border bg-card p-6 sm:p-10"><h1 className="text-3xl font-bold">Free Website Audit</h1><p className="mt-2 text-muted-foreground">Get a real mobile Performance and SEO snapshot.</p><form onSubmit={audit} className="mt-6 flex gap-2"><input required className="flex-1 rounded-xl border p-3" placeholder="https://yourwebsite.com" value={url} onChange={x=>setUrl(x.target.value)}/><button className="rounded-xl bg-portfolio-primary px-5 text-white">{loading?"Checking...":"Audit"}</button></form>{error&&<p className="mt-4 text-sm text-rose-600">{error}</p>}{report&&<div className="mt-6 space-y-5"><div className="grid grid-cols-2 gap-4"><Score label="Performance" value={report.performance}/><Score label="SEO" value={report.seo}/></div><div className="rounded-2xl bg-muted p-5">{report.performance<60?"Priority: improve mobile speed, images, and unused scripts.":report.seo<70?"Priority: improve page titles, headings, descriptions, and content structure.":"Your foundation is healthy. Review your key pages and conversion path next."}</div><div className="rounded-2xl border p-5"><b>Send me practical website tips</b>{saved?<p className="mt-2 text-emerald-600">Saved. Check your email for the confirmation.</p>:<><input type="email" className="mt-3 w-full rounded-xl border p-3" placeholder="you@email.com" value={email} onChange={x=>setEmail(x.target.value)}/><label className="mt-3 block text-sm"><input type="checkbox" required/> I agree to receive my audit follow-up and occasional practical website tips.</label><button type="button" onClick={saveLead} className="mt-4 rounded-xl bg-portfolio-primary px-4 py-2 text-white">Save my audit</button></>}</div></div>}</div></main> }
function Score({label,value}:{label:string,value:number}){return <div className="rounded-2xl bg-muted p-5"><b>{label}</b><p className="text-4xl">{value}</p><p className="text-sm">{value<50?"Needs attention":value<80?"Can improve":"Healthy"}</p></div>}
