import { ArrowLeft, BarChart3, ExternalLink } from "lucide-react"
import { redirect } from "next/navigation"
import { DashboardSignOutButton } from "@/components/dashboard-sign-out-button"
import { createSupabaseServerClient, isSupabaseConfigured } from "@/lib/supabase/server"

export default async function ReportsPage() {
  if (!isSupabaseConfigured()) redirect("/dashboard")
  const supabase = await createSupabaseServerClient()
  if (!supabase) redirect("/dashboard")
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) redirect("/dashboard/login")
  const { data } = await supabase.from("audit_leads").select("id, website_url, email, performance, seo, audit_source, status, created_at").order("created_at", { ascending: false }).limit(250)
  const reports = (data ?? []) as Array<{ id: string; website_url: string; email: string; performance: number | null; seo: number; audit_source: string; status: string; created_at: string }>
  return <main className="min-h-screen bg-slate-50 px-5 py-8 text-slate-950 sm:px-8"><div className="mx-auto max-w-6xl"><header className="flex flex-wrap items-end justify-between gap-5 border-b border-slate-200 pb-7"><div><a href="/dashboard/upcoming" className="inline-flex items-center gap-2 text-sm font-semibold text-sky-700 hover:text-sky-900"><ArrowLeft className="size-4" />Upcoming features</a><div className="mt-5 flex items-center gap-3"><span className="flex size-10 items-center justify-center rounded-xl bg-sky-100 text-sky-700"><BarChart3 className="size-5" /></span><div><p className="text-sm font-bold uppercase tracking-[.16em] text-sky-700">Client-ready reports</p><h1 className="mt-1 text-3xl font-bold tracking-tight">Report library</h1></div></div><p className="mt-4 text-sm leading-6 text-slate-600">Browse saved audit snapshots and open the complete lead workspace for follow-up.</p></div><DashboardSignOutButton /></header><section className="mt-8 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 p-5"><h2 className="font-bold">Saved reports</h2><p className="mt-1 text-sm text-slate-500">{reports.length} report{reports.length === 1 ? "" : "s"} available.</p></div>{reports.length ? <div className="divide-y divide-slate-100">{reports.map((report) => <article key={report.id} className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><p className="truncate font-bold">{report.website_url}</p><p className="mt-1 text-sm text-slate-600">{report.email} · {new Date(report.created_at).toLocaleDateString()}</p></div><div className="flex flex-wrap gap-2 text-xs font-semibold"><span className="rounded-full bg-sky-50 px-2.5 py-1 text-sky-700">Mobile {report.performance === null ? "—" : report.performance}</span><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-emerald-700">SEO {report.seo}</span><span className="rounded-full bg-slate-100 px-2.5 py-1 text-slate-600">{report.status}</span></div><a href={`/dashboard/leads/${report.id}`} className="inline-flex min-h-10 items-center justify-center gap-2 rounded-xl bg-slate-950 px-3 text-sm font-semibold text-white">Open report <ExternalLink className="size-4" /></a></article>)}</div> : <div className="p-12 text-center text-sm text-slate-600">Saved audit reports will appear here after visitors request a detailed report.</div>}</section></div></main>
}
